terrain_types:
  mountain:
    name: "Massive Mountain Range"
    description: "One enormous mountain range spanning the entire area"
    height_range: [120, 300]
    noise_algorithms:
      - type: "mountain_spine"
        frequency: 0.001
        amplitude_factor: 2.0
        octaves: 8
        power: 3.5
        lacunarity: 2.5
        persistence: 0.6
        ridge_sharpness: 4.0
      - type: "continental_ridges"
        frequency: 0.0005
        amplitude_factor: 1.5
        octaves: 6  
        power: 2.8
        ridge_offset: 1.0
      - type: "massive_elevation"
        frequency: 0.0008
        amplitude_factor: 1.8
        octaves: 5
        power: 4.2
        elevation_bias: 0.7
    biome_conditions:
      elevation_min: 0.65
      temperature_range: [-1, 0.4]
      moisture_range: [0.2, 0.8]
    features:
      - peaks
      - cliffs
      - valleys

  desert:
    name: "Desert Dunes"
    description: "Rolling sand dunes and rocky outcrops"
    height_range: [8, 25]
    noise_algorithms:
      - type: "dune_noise"
        frequency: 0.012
        amplitude_factor: 0.7
        octaves: 2
        power: 1.5
      - type: "ripple_noise"
        frequency: 0.025
        amplitude_factor: 0.3
        octaves: 1
      - type: "fine_sand"
        frequency: 0.15
        amplitude_factor: 0.1
        octaves: 1
    biome_conditions:
      temperature_min: 0.6
      moisture_max: 0.4
      elevation_range: [0.3, 0.7]
    features:
      - dunes
      - oases
      - rock_formations

  forest:
    name: "Dense Forest"
    description: "Rolling hills covered in thick vegetation"
    height_range: [15, 40]
    noise_algorithms:
      - type: "rolling_hills"
        frequency: 0.01
        amplitude_factor: 0.6
        octaves: 3
      - type: "tree_variation"
        frequency: 0.03
        amplitude_factor: 0.4
        octaves: 2
      - type: "root_system"
        frequency: 0.08
        amplitude_factor: 0.2
        octaves: 1
    biome_conditions:
      moisture_min: 0.55
      temperature_min: 0.35
      elevation_range: [0.4, 0.8]
    features:
      - clearings
      - streams
      - dense_canopy

  swamp:
    name: "Wetland Swamp"
    description: "Flat marshland with occasional mounds"
    height_range: [2, 12]
    noise_algorithms:
      - type: "flat_base"
        frequency: 0.006
        amplitude_factor: 0.3
        octaves: 1
      - type: "mound_spots"
        frequency: 0.04
        amplitude_factor: 0.5
        octaves: 1
        threshold: 0.3
      - type: "bog_detail"
        frequency: 0.2
        amplitude_factor: 0.1
        octaves: 1
    biome_conditions:
      elevation_max: 0.35
      moisture_min: 0.5
    features:
      - water_pools
      - mud_flats
      - vegetation_mounds

  tundra:
    name: "Arctic Tundra"
    description: "Windswept frozen terrain"
    height_range: [5, 20]
    noise_algorithms:
      - type: "windswept"
        frequency: 0.008
        amplitude_factor: 0.5
        octaves: 2
      - type: "permafrost_bumps"
        frequency: 0.04
        amplitude_factor: 0.3
        octaves: 1
        absolute: true
      - type: "ice_detail"
        frequency: 0.12
        amplitude_factor: 0.2
        octaves: 1
    biome_conditions:
      temperature_max: 0.35
    features:
      - permafrost
      - ice_patches
      - sparse_vegetation

  marsh:
    name: "Boggy Marsh"
    description: "Uneven wetland with grass tufts"
    height_range: [3, 15]
    noise_algorithms:
      - type: "bog_base"
        frequency: 0.015
        amplitude_factor: 0.4
        octaves: 2
      - type: "water_channels"
        frequency: 0.06
        amplitude_factor: 0.6
        octaves: 1
        threshold: 0.2
      - type: "grass_tufts"
        frequency: 0.25
        amplitude_factor: 0.15
        octaves: 1
    biome_conditions:
      elevation_max: 0.45
      moisture_min: 0.35
    features:
      - channels
      - reed_beds
      - muddy_patches

  grassland:
    name: "Rolling Plains"
    description: "Gentle hills and open meadows"
    height_range: [10, 30]
    noise_algorithms:
      - type: "gentle_hills"
        frequency: 0.01
        amplitude_factor: 0.6
        octaves: 3
      - type: "meadow_variation"
        frequency: 0.025
        amplitude_factor: 0.3
        octaves: 2
      - type: "grass_detail"
        frequency: 0.1
        amplitude_factor: 0.1
        octaves: 1
    biome_conditions:
      default: true
    features:
      - meadows
      - gentle_slopes
      - scattered_trees

generation_parameters:
  chunk_variation_strength: 0.4
  transition_smoothing: 0.15
  edge_blending_distance: 12
  feature_spawn_chance: 0.15
  unique_seed_multipliers: [73, 137, 241, 359, 467, 587, 719, 829]
  
  # Variable chunk sizing for scale-appropriate terrain features
  chunk_size_variants:
    - size: 32          # Small detailed chunks for local variation
      scale_factor: 0.5
      detail_level: "high"
      use_cases: ["caves", "ruins", "detailed_forest"]
      
    - size: 64          # Standard chunks for most terrain
      scale_factor: 1.0 
      detail_level: "medium"
      use_cases: ["grassland", "forest", "desert", "swamp"]
      
    - size: 128         # Large chunks for major terrain features  
      scale_factor: 2.0
      detail_level: "low"
      use_cases: ["mountain_ranges", "large_valleys", "major_rivers"]
      
    - size: 256         # Massive chunks for continental features
      scale_factor: 4.0
      detail_level: "continental" 
      use_cases: ["mountain_systems", "large_deserts", "ocean_basins"]

  # Rules for dynamic chunk size selection
  chunk_sizing_rules:
    mountain:
      preferred_sizes: [512, 768]    # Mountains are MASSIVE single features
      min_cluster_size: 1            # One chunk = one mountain
      grid_scale: true               # Scale to fill entire visible grid
      
    desert: 
      preferred_sizes: [384, 512]    # Deserts are vast single expanses
      min_cluster_size: 1
      grid_scale: true
      
    ocean:
      preferred_sizes: [768, 1024]   # Oceans are enormous
      min_cluster_size: 1
      grid_scale: true
      
    grassland:
      preferred_sizes: [256, 384]    # Rolling plains as single vista
      min_cluster_size: 1
      grid_scale: false
      
    forest:
      preferred_sizes: [256, 384]    # Forests as single biomes
      min_cluster_size: 1
      grid_scale: false
      
    swamp:
      preferred_sizes: [128, 192]    # Swamps are more localized
      min_cluster_size: 1
      grid_scale: false
      
    tundra:
      preferred_sizes: [384, 512]    # Tundra spans vast areas
      min_cluster_size: 1
      grid_scale: true