profiles:
  default:
    algorithm: perlin
    frequency: 2.5
    amplitude: 1.0
    octaves: 4
    persistence: 0.5
    lacunarity: 2.0
    minHeight: -100
    maxHeight: 100
    erosionIterations: 0
    smoothingPasses: 0
    turbulent: false
    steps: 1
    xSize: 128
    ySize: 128
    biomes:
      - name: water
        heightRange: [0.0, 0.25]
      - name: beach
        heightRange: [0.25, 0.35]
      - name: plains
        heightRange: [0.35, 0.6]
      - name: forest
        heightRange: [0.6, 0.8]
      - name: mountain
        heightRange: [0.8, 0.95]
      - name: snow
        heightRange: [0.95, 1.0]